### ISSUE TITLE
Add hiqp_examples package

### ISSUE THREAD

**Issue by rtkg** [OrebroUniversity/hiqp#23]
Might be nice to have a separate package containing launch files, config files and some shell scripts to let users play around with hiqp. This package could, e.g., depend on the yumi packages (which, eventually will be released in the ROS ecosystem).

**Comment by neckutrek** [comment]
Done, latest on devel.
A later dependency on yumi sounds good! Along with a stand-along example robot for demonstrating hiqp.

**Comment by rtkg** [comment]
Can we remove hiqp_examples from master - it has an implicit yumi dependency? To be replaced with the newly created hiqp_demos package in a separate repository (still under development): git@github.com:OrebroUniversity/hiqp_demos.git

**Comment by rtkg** [comment]
removed hiqp_examples on master
