### ISSUE TITLE
Let TaskManager output ddq* instead of dq*

### ISSUE THREAD

**Issue by neckutrek** [OrebroUniversity/hiqp#24]
If HiQP is made to output desired joint accelerations, simple numeric integration can be used to produce a desired trajectory (q*, dq*, ddq*) that can be followed by a tracking controller.
Outputting ddq* also allows for implementing an effort interface based controller by using an inverse dynamics solver together with measured dq and ddq*.

**Problem:** Calculating ddq* requires measuring dq which might not be available on all robots. TaskManager should therefore have two options, one to compute desired joint velocities, and one to compute desired joint accelerations!

The software engineering process of creating this feature is:
0. make a new compute_ddq branch to develop on. Keep this development separate from master/devel until fully functioning!
1. Do code revision on the GeometricProjection and GeometricAlignment task definitions. Rationalize them so that all e and J are calculated from the same function that takes two points (projection) or two lines (alignment) as parameters. This is to facilitate for implementing the calculation of dJ later.
2. Make a design change proposition for how to introduce calculation of dde* and dJ in the framework. This should be pretty straight forward.
3. Analyze the maths for how to express dJ when the points (projection) or lines (alignment) are shifted away from their parent link frame. (Similar to how J is computed).
4. Analyze the maths for how to express all the currently available task dynamics in dde* instead of de* (perhaps add an interface to task dynamics so that one can get both de* and dde* from different methods? to allow for calculating only dq*.)
5. Add 2 controllers: one inverse dynamics controller (based on ID-solver from kdl), and one position controller (dq* with integration)
6. If the ability to compute dq* from TaskManager is removed, the velocity controller needs to be altered.
7. Implement all and test all task definitions and all task dynamics.
8. push to master and devel.

**Comment by tstoyanov** [comment]
Implemented by @rtkg some time ago, so I am closing the issue.
