### ISSUE TITLE
Return result with services

### ISSUE THREAD

**Issue by ksatyaki** [OrebroUniversity/hiqp#26]
Return proper result for all service calls. 
For example, `list_all_primitives` should return a vector of strings.

At the moment, there are no return values (except a success, which IMHO has no meaning here) for the service calls.

**Comment by ksatyaki** [comment]
One thing I immediately see is that, the `GeometricPrimitive` abstract class should also include a `virtual std::vector <float> getParameters() = 0` interface to be able to return the primitive's parameters as a vector. This can then be returned by the `TaskManager`'s `getAllPrimitives()` function (will be defined).

**Comment by neckutrek** [comment]
Yes.

**Comment by ksatyaki** [comment]
Merged into devel-chitt. Awaiting merge into devel.
